name = "Sky Frogs"
author = "Flatts3000"
version = "0.0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ce8016b295eb02d8d9ad2efdf9a746f635fd2223f6fdd9e56a76daaf6744f20"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
