name = "Sky Frogs"
author = "Flatts3000"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa298b08b3c493d3f633e0a91a05b0220cff51025ea9563cfd25a4ad3831a5a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
