"""Generate Froglight -> Slime-in-a-Bucket crafting recipes from PF variant data.

For EVERY slime variant, a shaped crafting recipe that turns the variant's own
Froglight back into its Slime in a Bucket:

    B F F      B = empty bucket        F = that tier's filler block
    F G F      G = the variant Froglight (center, consumed)
    S S S      S = sweetslime

    -> 1 of that variant's Slime in a Bucket

The Froglight is the player's proof they already have the frog, so this is a
recovery / scaling path (remake a slime, and thus a frog, from a froglight) -
it does NOT bypass the froglight-check law: you must already hold the froglight.

The tier filler matches the slime chains / Dissolution Chamber (see
project_tier_filler_blocks): Cave=stone, Geode=gravel, Bog=mossy_cobblestone,
Tide=mycelium, Infernal=prismarine, Void=soul_soil.

Modded variants are guarded by their mod's load condition, taken straight from
the variant JSON's neoforge:conditions. The PF jar is the source of truth;
re-run this on every PF pin bump (alongside gen_singularities / gen_completionist).

Emits pack/kubejs/server_scripts/froglight_slime_recipes.js.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pf_jar  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "pack", "kubejs", "server_scripts", "froglight_slime_recipes.js")

FILLER = {
    "cave": "minecraft:stone",
    "geode": "minecraft:gravel",
    "bog": "minecraft:mossy_cobblestone",
    "tide": "minecraft:mycelium",
    "infernal": "minecraft:prismarine",
    "void": "minecraft:soul_soil",
}


def modid_of(data: dict) -> str | None:
    """The mod_loaded modid guarding this variant, or None for vanilla."""
    for cond in data.get("neoforge:conditions", []):
        if cond.get("type") == "neoforge:mod_loaded":
            return cond.get("modid")
    return None


def main() -> None:
    jar = pf_jar.find_jar(None)
    if not jar:
        print("PF jar not found - run tools/sync_instance.py first.")
        sys.exit(1)

    rows: list[tuple[str, str, str, str | None]] = []
    skipped: list[tuple[str, str]] = []
    for variant, data in sorted(pf_jar.load_variants(jar).items()):
        cat = str(data.get("category", "")).lower()
        filler = FILLER.get(cat)
        if not filler:
            skipped.append((variant, cat))
            continue
        rows.append((variant, cat, filler, modid_of(data)))

    out: list[str] = []
    out.append("// Sky Frogs - Froglight -> Slime in a Bucket crafting recipes.")
    out.append("//")
    out.append("// GENERATED by tools/gen_froglight_slime_recipes.py from PF slime_variant")
    out.append("// data. Do not edit by hand; re-run on every PF pin bump.")
    out.append("//")
    out.append("// Once you hold a variant's Froglight (proof you have the frog), craft it")
    out.append("// back into that variant's Slime in a Bucket. A recovery/scaling path that")
    out.append("// respects the froglight-check law (you must already have the froglight).")
    out.append("//")
    out.append("//   B F F   B = empty bucket          F = that tier's filler block")
    out.append("//   F G F   G = the variant Froglight (center, consumed)")
    out.append("//   S S S   S = sweetslime")
    out.append("")
    out.append("ServerEvents.recipes(event => {")
    for variant, cat, filler, modid in rows:
        result = (
            'productivefrogs:slime_bucket[minecraft:bucket_entity_data='
            '{Variant:"productivefrogs:%s",Category:"%s"}]' % (variant, cat.upper())
        )
        froglight = (
            "{ type: 'neoforge:components', items: ['productivefrogs:configurable_froglight'], "
            "components: { 'productivefrogs:slime_variant': 'productivefrogs:%s' } }" % variant
        )
        ind = "  "
        if modid:
            out.append("  if (Platform.isLoaded('%s')) {" % modid)
            ind = "    "
        out.append("%sevent.shaped(" % ind)
        out.append("%s  '%s'," % (ind, result))
        out.append("%s  ['BFF', 'FGF', 'SSS']," % ind)
        out.append("%s  {" % ind)
        out.append("%s    B: 'minecraft:bucket'," % ind)
        out.append("%s    F: '%s'," % (ind, filler))
        out.append("%s    S: 'productivefrogs:sweetslime'," % ind)
        out.append("%s    G: %s" % (ind, froglight))
        out.append("%s  }" % ind)
        out.append("%s).id('kubejs:froglight_slime/%s')" % (ind, variant))
        if modid:
            out.append("  }")
    out.append("})")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("Wrote %d froglight->slime recipes to %s" % (len(rows), os.path.relpath(OUT, REPO)))
    if skipped:
        print("Skipped %d variants with no tier filler:" % len(skipped), skipped)


if __name__ == "__main__":
    main()
